package newpackage;
import java.util.ArrayList;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import myfirstapplication.*;
/*
 change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Verbal
 */
public class SuperMarket extends javax.swing.JFrame {
    public SuperMarket() throws IOException {
        initComponents();
        products = new Product_List() {};
        basket = new Basket();
        orders = new Order_List();
        
        theUser = new USER();
        bas = new Basket();
        jMainTabbedPane.removeAll();
        jMainTabbedPane.addTab("Login", jPanel1);
Images = new ArrayList<>();
        products.LoadFromFile();
        orders.LoadFromFile();
        bas.Display_TA(jProductTextArea2);
        bas.LoadToTable(jProductsTable1);
        products.LoadToTable(PRODUCT_table);
     int qtyy=0;
     double pricee=0.0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        username_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginButtonClick = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        CloseButtonClick = new javax.swing.JButton();
        RegisterButtonClick = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jProductsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PRODUCT_table = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Add_Basket = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jProductPanel = new javax.swing.JPanel();
        jProductIDProductsLabel = new javax.swing.JLabel();
        PID_textField = new javax.swing.JTextField();
        jProductNameLabel = new javax.swing.JLabel();
        jWeightLabel = new javax.swing.JLabel();
        jPriceLabel = new javax.swing.JLabel();
        ExpDate_spinner = new javax.swing.JSpinner();
        jExpiryDateLabel = new javax.swing.JLabel();
        jEstimatedOrderDateLabel = new javax.swing.JLabel();
        ETA_spinner = new javax.swing.JSpinner();
        jCategoryLabel = new javax.swing.JLabel();
        jMinimumQuantityLabel = new javax.swing.JLabel();
        jMaximumQuantityLabel = new javax.swing.JLabel();
        PName_text_field = new javax.swing.JTextField();
        category_textField = new javax.swing.JTextField();
        weight_textField = new javax.swing.JTextField();
        price_textField = new javax.swing.JTextField();
        attach_Button = new javax.swing.JButton();
        minqty_textField = new javax.swing.JTextField();
        maxqty_spinner = new javax.swing.JTextField();
        ADD_button = new javax.swing.JButton();
        Edit_BUTTON = new javax.swing.JButton();
        SEARCH_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jProductTextArea = new javax.swing.JTextArea();
        jStockQuantityLabel = new javax.swing.JLabel();
        stockqty_textField = new javax.swing.JTextField();
        jManufacturedByLabel = new javax.swing.JLabel();
        manufacture_textField = new javax.swing.JTextField();
        jManufacturedDateLabel = new javax.swing.JLabel();
        LastDate_Spinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        ManufactureDate_spinner = new javax.swing.JSpinner();
        jManufacturedDateLabel1 = new javax.swing.JLabel();
        jReOrderPanel = new javax.swing.JPanel();
        jSupplierAddressLabel = new javax.swing.JLabel();
        DeliveryDate_spinner = new javax.swing.JSpinner();
        jDeliveryDateLabel = new javax.swing.JLabel();
        jSupplierNameLabel = new javax.swing.JLabel();
        orderID_textField = new javax.swing.JTextField();
        supplierName_textField = new javax.swing.JTextField();
        address_textField = new javax.swing.JTextField();
        jProductIDOrdersLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        order_TextArea = new javax.swing.JTextArea();
        PIDorder_textField = new javax.swing.JTextField();
        jOrderIDLabel = new javax.swing.JLabel();
        searchorder_button = new javax.swing.JButton();
        Order_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jProductsTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jProductTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jProductsTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_TextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("PASSWORD:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("USERNAME: ");

        LoginButtonClick.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LoginButtonClick.setText("LOGIN");
        LoginButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonClickActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        CloseButtonClick.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CloseButtonClick.setText("CLOSE");
        CloseButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonClickActionPerformed(evt);
            }
        });

        RegisterButtonClick.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        RegisterButtonClick.setText("REGISTER");
        RegisterButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonClickActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee", "Customer", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel4.setText("ROLE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(245, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegisterButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(CloseButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(username_TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(154, 154, 154))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterButtonClick, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jMainTabbedPane.addTab("LOGIN", jPanel1);

        PRODUCT_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "VAT Price", "Items in Stock", "Minimum allowed ", "Maximum allowed", "Stock Status", "Category"
            }
        ));
        PRODUCT_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRODUCT_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(PRODUCT_table);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Electronics", "Eatery", "Drinks", "Snacks", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Category: ");

        Add_Basket.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Add_Basket.setText("Add to Basket");
        Add_Basket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_BasketActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane7.setViewportView(jTextArea2);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("MORE INFORMATION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jProductsPanelLayout = new javax.swing.GroupLayout(jProductsPanel);
        jProductsPanel.setLayout(jProductsPanelLayout);
        jProductsPanelLayout.setHorizontalGroup(
            jProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductsPanelLayout.createSequentialGroup()
                .addGroup(jProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jProductsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jProductsPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jProductsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(Add_Basket, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton5)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jProductsPanelLayout.setVerticalGroup(
            jProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_Basket, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jMainTabbedPane.addTab("Display Products", jProductsPanel);

        jProductIDProductsLabel.setText("ID:");

        jProductNameLabel.setText("Name:");

        jWeightLabel.setText("Weight:");

        jPriceLabel.setText("Price:");

        ExpDate_spinner.setModel(new javax.swing.SpinnerDateModel());
        ExpDate_spinner.setEditor(new javax.swing.JSpinner.DateEditor(ExpDate_spinner, "dd/MM/yyyy"));

        jExpiryDateLabel.setText("Expiry Date:");

        jEstimatedOrderDateLabel.setText("Estimated Order Date:");

        ETA_spinner.setModel(new javax.swing.SpinnerDateModel());
        ETA_spinner.setEditor(new javax.swing.JSpinner.DateEditor(ETA_spinner, "dd/MM/yyyy"));

        jCategoryLabel.setText("Category:");

        jMinimumQuantityLabel.setText("Minimum Allowed:");

        jMaximumQuantityLabel.setText("Maximum Quantity:");

        attach_Button.setText("Attach Images");
        attach_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_ButtonClick(evt);
            }
        });

        ADD_button.setText("Add");
        ADD_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_buttonClick(evt);
            }
        });

        Edit_BUTTON.setText("Edit");
        Edit_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_BUTTONClick(evt);
            }
        });

        SEARCH_button.setText("Search");
        SEARCH_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_buttonClick(evt);
            }
        });

        jProductTextArea.setColumns(20);
        jProductTextArea.setRows(5);
        jScrollPane1.setViewportView(jProductTextArea);

        jStockQuantityLabel.setText("Stock Quantity:");

        jManufacturedByLabel.setText("Manufactured By:");

        jManufacturedDateLabel.setText("Manufactured Date:");

        LastDate_Spinner.setModel(new javax.swing.SpinnerDateModel());
        LastDate_Spinner.setEditor(new javax.swing.JSpinner.DateEditor(LastDate_Spinner, "dd/MM/yyyy"));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ManufactureDate_spinner.setModel(new javax.swing.SpinnerDateModel());
        ManufactureDate_spinner.setEditor(new javax.swing.JSpinner.DateEditor(ManufactureDate_spinner, "dd/MM/yyyy"));

        jManufacturedDateLabel1.setText("Last date:");

        javax.swing.GroupLayout jProductPanelLayout = new javax.swing.GroupLayout(jProductPanel);
        jProductPanel.setLayout(jProductPanelLayout);
        jProductPanelLayout.setHorizontalGroup(
            jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductPanelLayout.createSequentialGroup()
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEstimatedOrderDateLabel)
                                    .addComponent(jProductIDProductsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCategoryLabel)
                                    .addComponent(jPriceLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(price_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ETA_spinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(PID_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                    .addComponent(category_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Edit_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jProductPanelLayout.createSequentialGroup()
                                            .addComponent(jMinimumQuantityLabel)
                                            .addGap(5, 5, 5)))
                                    .addComponent(jManufacturedByLabel))
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jProductPanelLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                                .addComponent(SEARCH_button)
                                                .addGap(40, 40, 40)
                                                .addComponent(ADD_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(manufacture_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minqty_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jProductPanelLayout.createSequentialGroup()
                                    .addGap(0, 551, Short.MAX_VALUE)
                                    .addComponent(jManufacturedDateLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(LastDate_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jProductPanelLayout.createSequentialGroup()
                                    .addGap(199, 199, 199)
                                    .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jProductPanelLayout.createSequentialGroup()
                                            .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jProductNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jExpiryDateLabel))
                                                .addComponent(jStockQuantityLabel))
                                            .addGap(33, 33, 33)
                                            .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(stockqty_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(PName_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(weight_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ExpDate_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jProductPanelLayout.createSequentialGroup()
                                            .addComponent(jMaximumQuantityLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(maxqty_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jProductPanelLayout.createSequentialGroup()
                                            .addComponent(jManufacturedDateLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(ManufactureDate_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(attach_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButton1)))
                        .addGap(47, 47, 47))
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jProductPanelLayout.setVerticalGroup(
            jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jProductPanelLayout.createSequentialGroup()
                            .addComponent(jProductIDProductsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(jPriceLabel)
                            .addGap(60, 60, 60)
                            .addComponent(jCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jEstimatedOrderDateLabel))
                        .addGroup(jProductPanelLayout.createSequentialGroup()
                            .addComponent(PID_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(price_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(category_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(ETA_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jProductNameLabel)
                            .addComponent(PName_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weight_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jExpiryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExpDate_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jStockQuantityLabel)
                            .addComponent(stockqty_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMinimumQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minqty_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMaximumQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxqty_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jManufacturedByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manufacture_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jManufacturedDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ManufactureDate_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)))
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit_BUTTON)
                            .addComponent(SEARCH_button)
                            .addComponent(ADD_button)
                            .addComponent(attach_Button)
                            .addComponent(jButton1)))
                    .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastDate_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jManufacturedDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Edit Product", jProductPanel);

        jSupplierAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSupplierAddressLabel.setText("Supplier Address:");

        DeliveryDate_spinner.setModel(new javax.swing.SpinnerDateModel());
        DeliveryDate_spinner.setEditor(new javax.swing.JSpinner.DateEditor(DeliveryDate_spinner, "dd/MM/yyyy"));

        jDeliveryDateLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDeliveryDateLabel.setText("Delivery Date:");

        jSupplierNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSupplierNameLabel.setText("Supplier Name:");

        jProductIDOrdersLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jProductIDOrdersLabel.setText("PID:");

        order_TextArea.setColumns(20);
        order_TextArea.setRows(5);
        jScrollPane2.setViewportView(order_TextArea);

        jOrderIDLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jOrderIDLabel.setText("Order ID:");

        searchorder_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchorder_button.setText("Search");
        searchorder_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchorder_buttonClick(evt);
            }
        });

        Order_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Order_Button.setText("Order");
        Order_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_ButtonClick(evt);
            }
        });

        javax.swing.GroupLayout jReOrderPanelLayout = new javax.swing.GroupLayout(jReOrderPanel);
        jReOrderPanel.setLayout(jReOrderPanelLayout);
        jReOrderPanelLayout.setHorizontalGroup(
            jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReOrderPanelLayout.createSequentialGroup()
                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReOrderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jReOrderPanelLayout.createSequentialGroup()
                                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jReOrderPanelLayout.createSequentialGroup()
                                        .addComponent(jDeliveryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DeliveryDate_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jReOrderPanelLayout.createSequentialGroup()
                                        .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSupplierAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOrderIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(orderID_textField)
                                            .addComponent(address_textField))))
                                .addGap(42, 42, 42)
                                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProductIDOrdersLabel)
                                    .addComponent(jSupplierNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supplierName_textField)
                                    .addComponent(PIDorder_textField)
                                    .addComponent(searchorder_button, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jReOrderPanelLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(Order_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jReOrderPanelLayout.setVerticalGroup(
            jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jOrderIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jProductIDOrdersLabel)
                        .addComponent(orderID_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PIDorder_textField))
                .addGap(65, 65, 65)
                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSupplierAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(address_textField)
                    .addComponent(jSupplierNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierName_textField))
                .addGap(102, 102, 102)
                .addGroup(jReOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDeliveryDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeliveryDate_spinner)
                    .addComponent(searchorder_button, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addComponent(Order_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Re-Order", jReOrderPanel);

        jProductsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "VAT Price", "Stock", "Minimum", "Maximum", "Status", "Category", "Quantity"
            }
        ));
        jProductsTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProductsTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jProductsTable1);

        jProductTextArea2.setColumns(20);
        jProductTextArea2.setRows(5);
        jScrollPane6.setViewportView(jProductTextArea2);

        jButton2.setText("CONFIRM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("PREVIOUS BASKET:");

        jButton7.setText("ADD TO WISHLIST");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(784, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(402, 402, 402)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );

        jMainTabbedPane.addTab("Basket", jPanel2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        jButton4.setText("CONFIRM ORDER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sort Code:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("TOTAL:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Account Number:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("CHECKOUT", jPanel3);

        jProductsTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "VAT Price", "Stock", "Minimum", "Maximum", "Status", "Category", "Quantity"
            }
        ));
        jProductsTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProductsTable2MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jProductsTable2);

        jButton6.setText("ADD TO BASKET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("WISHLIST", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 965, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Order_ButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_ButtonClick
        String OrderID = orderID_textField.getText();
        String ProductID = PIDorder_textField.getText();
        String SuplierName = supplierName_textField.getText();
        String SuplierAddress = address_textField.getText();
       
        Product pt = products.find(ProductID);
        Date DeliveryDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            DeliveryDate = sdf.parse(sdf.format(DeliveryDate_spinner.getValue()));
        } catch (Exception e) { 
            return;
        }
        double TotalAmount = pt.CalculateTotalAmount();
        if(TotalAmount == 0.0) {
            return;
        }

        Order order = orders.find(OrderID);
        if(order == null) {
          
            products.editProduct(products.find(ProductID), pt);
            products.SaveToFile();
            order = new Order(OrderID, ProductID, DeliveryDate, TotalAmount, SuplierName, SuplierAddress);
            orders.newOrder(order);
            orders.SaveToFile();
            order_TextArea.setText("");
            order.Display(order_TextArea);
        } else {
        }
    }//GEN-LAST:event_Order_ButtonClick

    private void searchorder_buttonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchorder_buttonClick
        String OrderID = orderID_textField.getText().trim();  
        Order order = orders.find(OrderID);
        if(order != null) {
            PIDorder_textField.setText(order.getProductID());
            supplierName_textField.setText(order.getSuplierName());
            address_textField.setText(order.getSuplierAddress());
            DeliveryDate_spinner.setValue(order.getDeliveryDate());
            order_TextArea.setText("");
            order.Display(order_TextArea);
    }//GEN-LAST:event_searchorder_buttonClick
    }
    private void SEARCH_buttonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_buttonClick
        String ProductID = PID_textField.getText().trim(); 
        Product product = products.find(ProductID);
        if(product != null) {
            if(product.getStockQuantity() < product.getMinimumQuantity()) {
                JOptionPane.showMessageDialog(this, "This product needs to be reordered!!!");
            }
            searchProduct = product;
            PName_text_field.setText(product.getProductName());
            category_textField.setText(product.getCategory());
            weight_textField.setText(product.getWeight());
            price_textField.setText(product.getPrice()+"");
            ExpDate_spinner.setValue(product.getExpiryDate());
            ETA_spinner.setValue(product.getEstimatedOrderDate());
            category_textField.setText(product.getCategory());
            stockqty_textField.setText(product.getStockQuantity()+"");
            minqty_textField.setText(product.getMinimumQuantity()+"");
            maxqty_spinner.setText(product.getMaximumQuantity()+"");
         
            manufacture_textField.setText(product.getManufacturedBy());
            LastDate_Spinner.setValue(product.getManufacturedDate());
            nImages = product.getImages();
          
            jProductTextArea.setText("");
            product.Display(jProductTextArea);
    }//GEN-LAST:event_SEARCH_buttonClick
    }
    private void Edit_BUTTONClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_BUTTONClick
       String ProductID =  searchProduct.getPID();
        String ProductName = PName_text_field.getText().trim();
        String Weight = weight_textField.getText().trim();
        String Category = category_textField.getText().trim();
        String ManufacturedBy = manufacture_textField.getText().trim();
        double Price;
        try {
            Price = Double.parseDouble(price_textField.getText().trim());
        } catch (Exception e) {
            return;
        }
        Date ExpiryDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            ExpiryDate = sdf.parse(sdf.format(ExpDate_spinner.getValue()));
        } catch (Exception e) {
            return;
        }
        Date EstimatedOrderDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            EstimatedOrderDate = sdf.parse(sdf.format(ETA_spinner.getValue()));
        } catch (Exception e) {
            return;
        }
       
        int StockQuantity;
        try {
            StockQuantity = Integer.parseInt(stockqty_textField.getText().trim());
        } catch (Exception e) {
            return;
        }
         Date LastOrderDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            LastOrderDate = sdf.parse(sdf.format(LastDate_Spinner.getValue()));
        } catch (Exception e) {
            return;
        }
        int MinimumQuantity;
        try {
            MinimumQuantity = Integer.parseInt(minqty_textField.getText().trim());
        } catch (Exception e) {
            return;
        }

        Date ManufacturedDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            ManufacturedDate = sdf.parse(sdf.format(LastDate_Spinner.getValue()));
        } catch (Exception e) {
            return;
        }

        if(StockQuantity < 0 || MinimumQuantity < 0) {
            return;
        }

        Product product = products.find(ProductID);

        if(product.getMaximumQuantity() < MinimumQuantity) {
            return;
        }

        product.Edit(ProductName, Weight, Price, ExpiryDate, EstimatedOrderDate, nImages, Category, StockQuantity, MinimumQuantity,LastOrderDate, ManufacturedBy, ManufacturedDate);
        product.CalculateVatPrice();
        products.editProduct( searchProduct, product);
        products.SaveToFile();
        products.LoadToTable(PRODUCT_table);
        jProductTextArea.setText("");
        product.Display(jProductTextArea);
    }//GEN-LAST:event_Edit_BUTTONClick

    private void ADD_buttonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_buttonClick
        String ProductID = PID_textField.getText();
        String ProductName = PName_text_field.getText();
        String Weight = weight_textField.getText();
        String Category = category_textField.getText();
        String ManufacturedBy = manufacture_textField.getText();
     
        double Price;
        try {
            Price = Double.parseDouble(price_textField.getText().trim());
        } catch (Exception e) {
            return;
        }
        Date ExpiryDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            ExpiryDate = sdf.parse(sdf.format(ExpDate_spinner.getValue()));
        } catch (Exception e) {
            return;
        }
        Date EstimatedOrderDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            EstimatedOrderDate = sdf.parse(sdf.format(ETA_spinner.getValue()));
        } catch (Exception e) {
            return;
        }
        int StockQuantity;
        try {
            StockQuantity = Integer.parseInt(stockqty_textField.getText().trim());
        } catch (Exception e) {
            return;
        }
        int MinimumQuantity;
        try {
            MinimumQuantity = Integer.parseInt(minqty_textField.getText().trim());
        } catch (Exception e) {
            return;
        }
        int MaximumQuantity;
        try {
            MaximumQuantity = Integer.parseInt(maxqty_spinner.getText().trim());
        } catch (Exception e) {
            return;
        }

        Date ManufacturedDate;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            ManufacturedDate = sdf.parse(sdf.format(LastDate_Spinner.getValue()));
        } catch (Exception e) {
            return;
        }

        if(StockQuantity < 0 || MinimumQuantity < 0 || MaximumQuantity < 0) {
            return;
        }

        if(MaximumQuantity < MinimumQuantity) {
            return;
        }

        Product product = products.find(ProductID);
      //  if(product == null) {
            product = new Product(ProductID, ProductName, Weight, Price, ExpiryDate, EstimatedOrderDate, Images, Category, StockQuantity, MinimumQuantity, MaximumQuantity, ManufacturedBy, ManufacturedDate);
            product.CalculateVatPrice();
            products.addProduct(product);
            products.SaveToFile();
            products.LoadToTable(PRODUCT_table);
            jProductTextArea.setText("");
      //  } else {
      //      jLabel1.setText("A product ["+ProductID+"] already exists in the system...");
       // }
        searchProduct = null;
    }//GEN-LAST:event_ADD_buttonClick

    private void attach_ButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attach_ButtonClick
      
    }//GEN-LAST:event_attach_ButtonClick

    private void LoginButtonClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonClickActionPerformed

      
        if(theUser.ReadFromFile(username_TextField.getText(), jPasswordField1.getText(),  (String)jComboBox2.getSelectedItem()))
        {
            jLabel17.setText("Nice Login");
            if( (String)jComboBox2.getSelectedItem() == "Customer")
            {
                System.out.println("Customer has logged in:");
                jMainTabbedPane.addTab("Display Products",jProductsPanel );
                  jMainTabbedPane.addTab("Order",jReOrderPanel);
                     jMainTabbedPane.addTab("Basket", jPanel2);
                      jMainTabbedPane.addTab("Checkout", jPanel3);
                       jMainTabbedPane.addTab("WISHLIST",  jPanel4);
           // jMainTabbedPane.setEnabledAt(1,true);
                     jMainTabbedPane.setEnabledAt(1,true);
                      jMainTabbedPane.setEnabledAt(2,true);
                       jMainTabbedPane.setEnabledAt(3,true);
                         jMainTabbedPane.setEnabledAt(4,true);
                     jMainTabbedPane.setEnabledAt(5,true);
                     jMainTabbedPane.setEnabledAt(6,true);
                    
            //    jMainTabbedPane.addTab("Edit Basket", jProductPanel1);
                //jMainTabbedPane.setSelectedIndex(0);
            }
            else
               jMainTabbedPane.removeAll();
               jMainTabbedPane.addTab("Login", jPanel1);  
                jMainTabbedPane.addTab("Display Products", jProductsPanel);
                jMainTabbedPane.addTab("Edit Products", jProductPanel);
                jMainTabbedPane.addTab("Order", jReOrderPanel);
               jMainTabbedPane.addTab("Basket", jPanel2);
                jMainTabbedPane.addTab("Checkout", jPanel3);
                    jMainTabbedPane.addTab("WISHLIST",  jPanel4); 
            //    jMainTabbedPane.addTab("Edit Basket", jProductPanel1);
                jMainTabbedPane.setSelectedIndex(0);
        }
        else if (!theUser.ReadFromFile(username_TextField.getText(), jPasswordField1.getText(),  (String)jComboBox2.getSelectedItem()))
        {
            jLabel17.setText("Cant Login");
        }
    }//GEN-LAST:event_LoginButtonClickActionPerformed

    private void CloseButtonClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonClickActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseButtonClickActionPerformed

    private void RegisterButtonClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonClickActionPerformed
        if( !theUser.isRegistered(username_TextField.getText(), jPasswordField1.getText(), (String)jComboBox2.getSelectedItem()))
        {

            jLabel2.setText("Cannot register the user...." );

        }

        else
        {
            jLabel17.setText("The "+ username_TextField.getText()+ " is registered ...... Please log in now  ");
    }//GEN-LAST:event_RegisterButtonClickActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
products.ReadFromFile();
        products.SaveToFile();
        products.LoadToTable(PRODUCT_table);
        // TODO add your handling code here:}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 int row_index = PRODUCT_table.getSelectedRow();  
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jProductsTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductsTable1MouseClicked
  
    }//GEN-LAST:event_jProductsTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
bas.SaveToFile(jProductsTable1);
        try {
            bas.Display_TA(jTextArea1);
        } catch (IOException ex) {
            Logger.getLogger(SuperMarket.class.getName()).log(Level.SEVERE, null, ex);
        }
        bas.getSum(jProductsTable1, jTextField3 );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jProductsTable1.getModel();

       // get selected row index

       try{
       int SelectedRowIndex = jProductsTable1.getSelectedRow();
       model.removeRow(SelectedRowIndex);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }
                                                   
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

 MainJFrame tframe2 = new MainJFrame();
        tframe2.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Add_BasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_BasketActionPerformed
        try {
            products.CopyJTable(PRODUCT_table, jProductsTable1);
        } catch (IOException ex) {
            Logger.getLogger(SuperMarket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Add_BasketActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String query = jComboBox1.getSelectedItem().toString();
        products.filter(PRODUCT_table, query);
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void PRODUCT_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRODUCT_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PRODUCT_tableMouseClicked

    private void jProductsTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductsTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jProductsTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            products.CopyJTable(jProductsTable2, jProductsTable1);
        } catch (IOException ex) {
          //  Logger.getLogger(SuperMarket.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try {
            products.CopyJTable(jProductsTable1, jProductsTable2);
        } catch (IOException ex) {
       //     Logger.getLogger(SuperMarket.class.getName()).log(Level.SEVERE, null, ex);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
 
    public static void main(String args[]) {
   
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SuperMarket().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SuperMarket.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            });
        
                
    }
USER theUser;
  Basket bas;
    ArrayList<String> Images;
    ArrayList<String> nImages;
    Product_List products;
    Basket basket;
    Order_List orders;
    Product searchProduct;
    Basket searchbasket;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_button;
    private javax.swing.JButton Add_Basket;
    private javax.swing.JButton CloseButtonClick;
    private javax.swing.JSpinner DeliveryDate_spinner;
    private javax.swing.JSpinner ETA_spinner;
    private javax.swing.JButton Edit_BUTTON;
    private javax.swing.JSpinner ExpDate_spinner;
    private javax.swing.JSpinner LastDate_Spinner;
    private javax.swing.JButton LoginButtonClick;
    private javax.swing.JSpinner ManufactureDate_spinner;
    private javax.swing.JButton Order_Button;
    private javax.swing.JTextField PID_textField;
    private javax.swing.JTextField PIDorder_textField;
    private javax.swing.JTextField PName_text_field;
    private javax.swing.JTable PRODUCT_table;
    private javax.swing.JButton RegisterButtonClick;
    private javax.swing.JButton SEARCH_button;
    private javax.swing.JTextField address_textField;
    private javax.swing.JButton attach_Button;
    private javax.swing.JTextField category_textField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jCategoryLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jDeliveryDateLabel;
    private javax.swing.JLabel jEstimatedOrderDateLabel;
    private javax.swing.JLabel jExpiryDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JLabel jManufacturedByLabel;
    private javax.swing.JLabel jManufacturedDateLabel;
    private javax.swing.JLabel jManufacturedDateLabel1;
    private javax.swing.JLabel jMaximumQuantityLabel;
    private javax.swing.JLabel jMinimumQuantityLabel;
    private javax.swing.JLabel jOrderIDLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jPriceLabel;
    private javax.swing.JLabel jProductIDOrdersLabel;
    private javax.swing.JLabel jProductIDProductsLabel;
    private javax.swing.JLabel jProductNameLabel;
    private javax.swing.JPanel jProductPanel;
    private javax.swing.JTextArea jProductTextArea;
    private javax.swing.JTextArea jProductTextArea2;
    private javax.swing.JPanel jProductsPanel;
    private javax.swing.JTable jProductsTable1;
    private javax.swing.JTable jProductsTable2;
    private javax.swing.JPanel jReOrderPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel jStockQuantityLabel;
    private javax.swing.JLabel jSupplierAddressLabel;
    private javax.swing.JLabel jSupplierNameLabel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jWeightLabel;
    private javax.swing.JTextField manufacture_textField;
    private javax.swing.JTextField maxqty_spinner;
    private javax.swing.JTextField minqty_textField;
    private javax.swing.JTextField orderID_textField;
    private javax.swing.JTextArea order_TextArea;
    private javax.swing.JTextField price_textField;
    private javax.swing.JButton searchorder_button;
    private javax.swing.JTextField stockqty_textField;
    private javax.swing.JTextField supplierName_textField;
    private javax.swing.JTextField username_TextField;
    private javax.swing.JTextField weight_textField;
    // End of variables declaration//GEN-END:variables

}